resource_group_name = "aks_terraform_rg"
location            = "West Europe"
cluster_name        = "terraform-aks"
kubernetes_version  = "1.26.3"
system_node_count   = 1
node_resource_group = "aks_terraform_resources_rg"
vnet_name           = "aks_custom_vnet"
address_space       = ["10.0.0.0/16"]
vmsubnet_ip         = ["10.0.1.0/24"]
private_cluster     = true
# subnet_name       = "aks_custom_subnet"